### ISSUE TITLE
Since upgrading to 1.3.15 various script calls from card tap_action with service data fail

### ISSUE THREAD

**Issue by profahmad** [UI-Lovelace-Minimalist/UI#1597]
I use a custom script to toggle lights and brightness from cards by passing in different variables. I was able to initiate these from the **card_room** and **card_light** cards but now get a version of the error in this bug: [https://github.com/UI-Lovelace-Minimalist/UI/issues/1566](https://github.com/UI-Lovelace-Minimalist/UI/issues/1566)

I fixed the card_room error by changing:

```
widget_icon_room:
  variables:
    tap_action:
      action: "toggle"
    hold_action:
      action: "more-info"
  tap_action:
    action: "[[[ return variables?.tap_action?.action ? variables.tap_action.action : 'none'; ]]]"
    entity: "[[[ return variables.tap_action.entity; ]]]"
    navigation_path: "[[[ return variables.tap_action.navigation_path; ]]]"
    url_path: "[[[ return variables.tap_action.url_path; ]]]"
    perform_action: "[[[ return variables.tap_action.service; ]]]"
    target: "[[[ return variables.tap_action.service_data; ]]]"
  hold_action:
    action: "[[[ return variables?.hold_action?.action ? variables.hold_action.action : 'none'; ]]]"
    entity: "[[[ return variables.hold_action.entity; ]]]"
    navigation_path: "[[[ return variables.hold_action.navigation_path; ]]]"
    url_path: "[[[ return variables.hold_action.url_path; ]]]"
    perform_action: "[[[ return variables.hold_action.service; ]]]"
    target: "[[[ return variables.hold_action.service_data; ]]]"
```

to:
```
widget_icon_room:
  variables:
    tap_action:
      action: "toggle"
    hold_action:
      action: "more-info"
  tap_action:
    action: "[[[ return variables?.tap_action?.action ? variables.tap_action.action : 'none'; ]]]"
    entity: "[[[ return variables.tap_action.entity; ]]]"
    navigation_path: "[[[ return variables.tap_action.navigation_path; ]]]"
    url_path: "[[[ return variables.tap_action.url_path; ]]]"
    perform_action: "[[[ return variables.tap_action.service; ]]]"
    service_data: "[[[ return variables.tap_action.service_data; ]]]"
  hold_action:
    action: "[[[ return variables?.hold_action?.action ? variables.hold_action.action : 'none'; ]]]"
    entity: "[[[ return variables.hold_action.entity; ]]]"
    navigation_path: "[[[ return variables.hold_action.navigation_path; ]]]"
    url_path: "[[[ return variables.hold_action.url_path; ]]]"
    perform_action: "[[[ return variables.hold_action.service; ]]]"
    service_data: "[[[ return variables.hold_action.service_data; ]]]"
```

I haven't found a fix for the **card_light** card, setting tap_action to 'call_service' and passing service data results in the error: _Failed to perform the action script/SCRIPT_NAME. not a valid value for dictionary value @ data['target']['entity_id']. Got ''_

**Comment by wilbiev** [comment]
Strange the release v1.3.15 should not affect card_room. This will be fixed in the next release. The proper code:
```
widget_icon_room:
  variables:
    tap_action:
      action: "toggle"
    hold_action:
      action: "more-info"
  tap_action:
    action: "[[[ return variables?.tap_action?.action ? variables.tap_action.action : 'none'; ]]]"
    entity: "[[[ return variables.tap_action.entity; ]]]"
    navigation_path: "[[[ return variables.tap_action.navigation_path; ]]]"
    url_path: "[[[ return variables.tap_action.url_path; ]]]"
    perform_action: "[[[ return variables.tap_action.service; ]]]"
    data: "[[[ return variables.tap_action.service_data; ]]]"
  hold_action:
    action: "[[[ return variables?.hold_action?.action ? variables.hold_action.action : 'none'; ]]]"
    entity: "[[[ return variables.hold_action.entity; ]]]"
    navigation_path: "[[[ return variables.hold_action.navigation_path; ]]]"
    url_path: "[[[ return variables.hold_action.url_path; ]]]"
    perform_action: "[[[ return variables.hold_action.service; ]]]"
    data: "[[[ return variables.hold_action.service_data; ]]]"
  size: "15px"
  color: "var(--google-grey)"
  show_icon: true
  show_name: false
  styles:
    icon:
      - width: "50%"
      - height: "50%"
      - line-height: "0"
      - color: "rgba(var(--color-theme),0.2)"
    img_cell:
      - border-radius: "50%"
      - background-color: "rgba(var(--color-theme),0.05)"
    grid:
      - grid-template-areas: "'i'"
    card:
      - height: "100%"
      - box-shadow: "none"
      - padding: "0px"
      - border-radius: "50%"
```

**Comment by profahmad** [comment]
Ah sweet, thanks for that. I've noticed a similar issue with other cards today, I have a few **card_generic** cards with service calls and data that have the same error.

**Comment by profahmad** [comment]
I've done a little digging through the template files and **action_cards** and noticed that _adaptive_ is the new term to pass to _ulm_card_tap_action_ in order to call a service with data. This works for my generic cards but not for the **light_card**, that default to opening a popup. Is there anything else I need to specify in my yaml to specifically call a service?

**Comment by profahmad** [comment]
With v1.3.16 **card_room** is now fixed, but any other use of **"call-service"** is throwing the same error, regardless of card template. Here's some example yaml:

```
- type: "custom:button-card"
  template: card_light
  entity: light.bedroom
  variables:
    ulm_name_tap_action: "call-service"
    ulm_name_tap_service: "script.control_light"
    ulm_name_tap_service_data:
      room: kitchen
```

It still works without issue in v1.3.10 which I've rolled back to. Any idea what's causing this?

**Comment by jonikarbu** [comment]
> With v1.3.16 **card_room** is now fixed, but any other use of **"call-service"** is throwing the same error, regardless of card template. Here's some example yaml:
> 
> ```
> - type: "custom:button-card"
>   template: card_light
>   entity: light.bedroom
>   variables:
>     ulm_name_tap_action: "call-service"
>     ulm_name_tap_service: "script.control_light"
>     ulm_name_tap_service_data:
>       room: kitchen
> ```
> 
> It still works without issue in v1.3.10 which I've rolled back to. Any idea what's causing this?

The double-tap actions of the card_light template had also stopped working for me. I updated to version v1.3.16, but the issue wasn't fixed yet.

**Comment by jonikarbu** [comment]
> With v1.3.16 **card_room** is now fixed, but any other use of **"call-service"** is throwing the same error, regardless of card template. Here's some example yaml:
> 
> ```
> - type: "custom:button-card"
>   template: card_light
>   entity: light.bedroom
>   variables:
>     ulm_name_tap_action: "call-service"
>     ulm_name_tap_service: "script.control_light"
>     ulm_name_tap_service_data:
>       room: kitchen
> ```
> 
> It still works without issue in v1.3.10 which I've rolled back to. Any idea what's causing this?

The double tap call-service actions of the card_light template had also stopped working for me. I updated to version v1.3.16, but the issue wasn't fixed yet

**Comment by profahmad** [comment]
It did fix it and adding the **__target_** variable to every other service call seems to have done the trick, thanks!

For my own understanding (without drilling deep into the code), why does the target variable need to be specified? What's its purpose? I tested specifying a random entity not related to the card being displayed or script being called and it seems to work regardless.

**Comment by wilbiev** [comment]
Great! Thank you for your reply. I will close this issue.
