### ISSUE TITLE
Scroll issue on popups

### ISSUE THREAD

**Issue by matrixx567** [UI-Lovelace-Minimalist/UI#928]
**Describe the bug**
A full screen popup has a white border and it enables scrolling by some pixels.
The white border is shown on all internal popups.

**Expected behavior**
There shouldn't be a white border and the popup shouldn't be scrollable.

**Screenshots**
![Screenshot 2022-08-06 16 28 10](https://user-images.githubusercontent.com/4608946/183253952-83435d6f-7db8-404b-a87d-12661cb496ed.png)

**Additional context**
Could the problem be in the implementation of the internal UI-Minimalist popups or is there a problem in the underlying library lovelace-card-tools by @thomasloven that is used by the browser_mod.

**Comment by AndyVRD** [comment]
I already fixed this, will commit the changes to a pr today.

**Comment by schumijo** [comment]
@matrixx567 @AndyVRD 
On which device and app/browser do you see this problem ?
I don't see any white border on Android Home Assistant app.

**Comment by matrixx567** [comment]
More or less I see it on all popups on all devices, on my Android Home Assistant app and also in the Chrome browser on my notebook.

The light popup on my Android has the white border but it doesn't scroll. The power_outlet popup has both, he white border and also the scrolling.

**Comment by schumijo** [comment]
@matrixx567 
Ok interesting 🤔
Maybe it depends on height resolution. 
Let see @AndyVRD fix

**Comment by AndyVRD** [comment]
I had this behavior on iOS and Chrome so it was not related to a specific resolution or OS. The strange thing about it was it's not always showing and had to multiple refresh to got the "glitch". I fixed it by applying the below style to all the browser_mod parts of the popup's. @schumijo, if you see more complains about it feel free to add this fix to the popup's.

```                  style:
                    .: |
                      :host {
                        --mdc-theme-surface: var(--primary-background-color);
                        --secondary-background-color: var(--primary-background-color);
                        --ha-card-background: var(--primary-background-color);
                      }
                      mwc-icon-button {
                        color: rgba(0,0,0,0);
                    $: |
                      .mdc-dialog .mdc-dialog__container .mdc-dialog__surface {
                        border-radius: 0px;
                      }
                      *{
                        --secondary-background-color: none;
                      }```

**Comment by matrixx567** [comment]
@AndyVRD

I've tested your code in the styles section of the power_outlet_stats popup but it doesn't fix the problem.

I think the white border has more to do with the padding of the following section

```css
.mdc-dialog .mdc-dialog__content {
    position: var(--dialog-content-position, relative);
    padding: var(--dialog-content-padding, 24px);
}
```
The variable `--dialog-content-padding` isn't set in my case.

**Comment by AndyVRD** [comment]
I have not tested it with all the popups but it works fine for the light card and media player card.

**Comment by matrixx567** [comment]
@AndyVRD This code is from the Chrome Dev Tools.

**Comment by matrixx567** [comment]
Hi @AndyVRD @schumijo,

If I add following style to the browser_mod style of an action than it will remove the white border and the scrollbar

```yaml
      style:
        $: |
          :host .mdc-dialog .mdc-dialog__container .mdc-dialog__surface .mdc-dialog__content {
            padding: 20px 24px;
          }
```



![image](https://user-images.githubusercontent.com/4608946/183745390-1450c14d-5f54-407e-8eb2-d1998cd29156.png)

**Comment by AndyVRD** [comment]
Yes and this will also remove the border-radius.

```                  style:
                    $: |
                      :host .mdc-dialog .mdc-dialog__container .mdc-dialog__surface .mdc-dialog__content {
                        padding: 20px 24px;
                      }
                      .mdc-dialog .mdc-dialog__container .mdc-dialog__surface {
                        border-radius: 0px;
                      }```

**Comment by schumijo** [comment]
Hi @AndyVRD @matrixx567 
I am in holidays and I can't do any tests before next week.

**Comment by matrixx567** [comment]
Hi @AndyVRD @schumijo 

An improved version for removing the border radius only on small devices if the popup is set to full screen

```yaml
      style:
        $: |
          :host .mdc-dialog .mdc-dialog__container .mdc-dialog__surface .mdc-dialog__content {
            padding: 20px 24px;
          }
          @media (max-width: 451px) or (max-height: 501px) {
            .mdc-dialog .mdc-dialog__container .mdc-dialog__surface {
              border-radius: 0px;
            }
          }
        .: |
          @media (max-width: 451px) or (max-height: 501px) {
            ha-dialog {
              --ha-card-border-radius: 0px;
            }
          }
          :host {
            --mdc-theme-surface: var(--primary-background-color);
          }
```
